# Katrin Erk March 2026
# methods for visualizing contextualized embeddings in the style of Context Atlas
import math
import torch
import numpy as np
from minicons import cwe
import matplotlib.pyplot as plt
from matplotlib import colormaps
import matplotlib.cm as cm
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import mplcursors
import pandas as pd
from sklearn.cluster import KMeans
import nltk
from collections import Counter, defaultdict
import zipfile
import json
import statistics
import scipy

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# compute embeddings using minicons
# expected input: a pandas data frame with columns including
# "sent" for sentence, "tgt" for target word
#
# the "what" parameter is for which column contains the word for which
# to compute contextualized embeddings. By default, it is 'tgt', but if
# you have columns for, say, the subject and direct object, you can use it for those too.
#
# Embeddings are computed in batches as minicons cannot handle
# very many sentences at the same time.
#
# layerlabel: which layers to use for embeddings. Implemented options:
# "last4" : last 4 layers
# "last" : last layer
# uppermid3: three layers around the layer at 2/3 the number of layers
# uppermid: layer at 2/3 the number of layers
#
# returns: a numpy array of embeddings, one per row.

def compute_embeddings_for(df, what = "tgt", layerlabel = "last4", batchsize = 100, modeltype = "'bert-base-uncased"):
    minicons_obj = cwe.CWE(modeltype)
    
    if layerlabel == "last4":
        layer = list(range(minicons_obj.layers + 1))[-4:]
    elif layerlabel == "uppermid3":
        midlayer = int(minicons_obj.layers * 2/3)
        layer = [midlayer-1, midlayer, midlayer + 1]
    elif layerlabel == "last":
        layer = -1
    elif layerlabel == "uppermid":
        layer = int(minicons_obj.layers * 2/3)
    else: raise Exception("unknown layer label " + layerlabel)

    embs = [ ]
    for startix in range(0, len(df), batchsize):
        inputs = [ (row["sent"], row[what]) for row in df.iloc[startix:startix + batchsize].to_dict( "records") ]
        these_embs = minicons_obj.extract_representation(inputs, layer = layer)
    
        if layerlabel == "last4" or layerlabel == "uppermid3":
            these_embs = torch.mean(torch.stack(these_embs), dim=0) 
            
        these_embs = these_embs.detach().numpy()
        embs.append(these_embs)

    embs = np.concatenate(embs, axis = 0)
    return embs

# Input: data frame including entries "sent", "tgt".
# This makes, for each of the rows of the data frame,
# a shortened version of "sent" including the target word
# and <windowsize> words on either side, by default 5.
#
# returns: list of sentence snippets, each as a string
def make_sentence_snippets(df, windowsize = 5):
    sentence_snippets = [ ]
    
    for row in df.to_dict("records"):
        words = row["sent"].split()

        # sanity check
        if row["tgt"] not in words:
            # store the original sentence in its entirety
            sentence_snippets.append(" ".join(words))
            continue
        
        # determine the index of the target word
        targetindex = words.index(row["tgt"])
        
        # window of 5 words left and right of the target, 
        # but don't go below 0 or above the length of the sentence
        snippet_start = max(0, targetindex - windowsize)
        snippet_end = min(snippet_start + 2 * windowsize + 1, len(words))
    
        # make the snippet, as a string
        snippet = words[snippet_start : snippet_end]
        sentence_snippets.append(" ".join(snippet))

    return sentence_snippets

# dimensinality reduction
# input: a numpy array of embeddings
# output: a 2-dimensional numpy array of embeddings
#
# implemented methods: "TSNE", "PCA"
def reduce_dim(embeddings, dimred_method = "TSNE"):
    if dimred_method == "PCA":
        twodim = PCA().fit_transform(np.array(embeddings))[:,:2]
    elif dimred_method == "TSNE":
        twodim = TSNE(n_components = 2, random_state = 0).fit_transform(np.array(embeddings))

    return twodim

# helper function: given one embedding (query), and an array of embeddings (X),
# determine the embedding from X that is most similar to query in terms of cosine.
#
# returns; index in X of nearest neighbor, similarity
#
# code generated by  Claude
def cosine_nn(query: np.ndarray, X: np.ndarray):
    """
    query: shape (d,)
    X:     shape (n, d)
    returns: (best_index, best_similarity)
    """
    # Ensure float dtype
    query = np.asarray(query, dtype=float)
    X = np.asarray(X, dtype=float)

    # L2 norms (add small eps to avoid division by zero)
    eps = 1e-12
    q_norm = np.linalg.norm(query) + eps
    X_norms = np.linalg.norm(X, axis=1) + eps

    # Cosine similarities: (X @ query) / (||X_i|| * ||q||)
    sims = (X @ query) / (X_norms * q_norm)

    best_idx = np.argmax(sims)
    return best_idx, sims[best_idx]


# clustering:
# group datapoints,
# return pointwise cluster labels,
# cluster centroids,
# and for each cluster, the datapoint closest to the centroid
#
# input: data frame with entries "sent", "tgt"
# embeddings for one word in each of the rows of the data frame
# number of clusters
#
def compute_clusters(embeddings, numclusters = 5, cluster_method = "kmeans"):
    ###
    # make the clusters
    if cluster_method == "kmeans":
        kmeans = KMeans(n_clusters=numclusters, random_state=0, n_init="auto")
        kmeans.fit(embeddings)
        clusterlabels = kmeans.labels_
        clustercentroids = kmeans.cluster_centers_
    else: raise Exception("unknown clustering method " + cluster_method)

    ####
    # for each cluster, designate a center point
    clustercentralmember = [ ]
    for clusterindex in range(numclusters):
        indices = [i for i in range(len(clusterlabels)) if clusterlabels[i] == clusterindex]
        indexindex, _ = cosine_nn(clustercentroids[clusterindex], embeddings[indices])
        # for now, just use the first sentence in the cluster
        clustercentralmember.append(indices[indexindex])


    return clusterlabels, clustercentroids, clustercentralmember

# compute tf/idf: given a list of documents, each of them a string,
# compute the tf/idf of each term in the documents.
# optionally exclude some words from analysis
def compute_tfidf(doclist, excludewords= []):
    # term frequency
    doc_tf = { }
    # document frequency: in how many pieces of the Brown corpus does each word appear
    dfreq = Counter()

    for docix, doc in enumerate(doclist):
        # compute word frequency for this cluster
        fd = nltk.FreqDist([w.lower() for w in doc if w.lower() not in excludewords])
        doc_tf[docix] = fd
        dfreq.update(list(fd.keys()))

    doc_tfidf = { }
    for docix in doc_tf.keys():
        doc_tfidf[ docix ] = { }
        for word, thistf in doc_tf[docix].items():
            this_idf = math.log( len(doclist) / dfreq[word] )
            doc_tfidf[docix][word] = thistf * this_idf

    return doc_tfidf

## drawing embeddings in two-dimensional downprojection:
# assuming that the downprojection has already been computed.
# each point is associated with a sentence snippet that
# is shown on hovering.
# 
#
# input:
# df: data frame with columns "sent", "tgt", for computing sentence snippets
# twodim: downprojection of embeddings
# pointcolors: if given, use to color embedding scatterplot. if not given, embeddings are grayish
# bigtexts: if given, triples (xcoord, ycoord, text) to be displayed in big letters and in color
#      on top of the scatterplot
# cfontsize: font size for the "bigtext"
def draw_points(df, twodim, pointcolors = None, bigtexts = None, ctfontsize=16):
    sentence_snippets = make_sentence_snippets(df)
    
    # set up the canvas
    fig, ax =  plt.subplots()
    fig.set_size_inches(8.5, 6.5)
    
    
    # add a scatter plot of the two-D embeddings
    if pointcolors is None:
        scatter = ax.scatter(twodim[:,0], twodim[:,1], edgecolors="dimgray", c="honeydew")
    else:
        scatter = ax.scatter(twodim[:,0], twodim[:,1], c=pointcolors, cmap = "viridis")
    cursor = mplcursors.cursor(scatter, hover=True)

    if bigtexts is not None:
        cmap = colormaps.get_cmap("plasma")
        for index, ctext in enumerate(bigtexts):
            word, xcoord, ycoord = ctext
            plt.text(xcoord, ycoord, word, fontweight = "bold", 
                     fontfamily = "fantasy", c = cmap(index/len(bigtexts)), fontsize = ctfontsize)

    
    @cursor.connect("add")
    def on_add(sel):
        i = sel.index
        sel.annotation.set_text(sentence_snippets[i])
        sel.annotation.set_fontsize(8)
        sel.annotation.set_fontfamily("DejaVu Sans")
        sel.annotation.set_color("black")
    
        
        box = sel.annotation.get_bbox_patch()
        box.set(fc="white", lw=0.8, alpha=0.9)  # fc=facecolor, ec=edgecolor
        box.set_boxstyle("round,pad=0.25")
    
        # sel.annotation.get_bbox_patch().set_visible(False)
    
    plt.show()

##
# my reimplementation of the now-defunct context atlas:
# given a data frame with sentences with a common target word,
# compute contextualized embeddings and visualize them in 2d,
# with sentence snippets visible as you hover over the points,
# and with indicative words of different regions of the space
# superimposed in big letters.
#
# input:
# df: data frame with columns "sent", "tgt", for computing sentence snippets
# what: column containing the target word
# embeddings: if given, don't recompute
# layerlabel: "last" or "last4", layers to use if embeddings are computed from scratch
# numclusters: number of clusters to use when grouping points into clusters for computing indicative words
# clustercolors: color in the clusters? if not, all points are silver
# modeltype: language model to use to compute embeddings
#
# returns: cluster label for each data point,
#          most indicative word for each cluster (dict clusterlabel -> word)
def contextatlas(df, what = "tgt", embeddings = None, layerlabel = "last4", numclusters = 5, showwords = True,
                     clustercolors = False, modeltype = 'bert-base-uncased'):
    ### obtain embeddings
    if embeddings is None:
        compute_embeddings_for(df, what = what, layerlabel = layerlabel, batchsize = 100, modeltype = modeltype)

    ### downproject for visualization
    twodim = reduce_dim(embeddings, dimred_method = "TSNE")

    ### obtain text for characterizing groups of points:
    # 1. cluster datapoints
    clusterlabels, clustercentroids, clustercentralpoints = compute_clusters(embeddings, numclusters = numclusters)

    # 2. compute tf/idf words for each cluster
    # for each cluster, select a smaller number of words centered on the target
    sentence_snippets = make_sentence_snippets(df, windowsize = 10)
    clusterwords = defaultdict(list)
    for ix, s in enumerate(sentence_snippets):
        clusterindex = clusterlabels[ix]
        words = s.split()
        clusterwords[ clusterindex ] += words

    # don't count the target word, or one of a small list of stopwords, in tf-idf
    excludewords = list(set([w.lower() for w in df.tgt]))
    excludewords += ["i", "you", "he", "she", "it", "they", "we", "us", "is", "was", "be", "do", "does", 
                      "did", "ca", "can"]

    # compute tf-idf
    cluster_tfidf = compute_tfidf([clusterwords[i] for i in range(numclusters)], excludewords= excludewords)
    # for each cluster, find the word with maximum tf-idf
    cluster_maxword = { }
    for clusterindex in range(numclusters):
        cluster_maxword[clusterindex] = sorted(cluster_tfidf[clusterindex].items(), \
                                               key = lambda p:p[1], reverse = True)[0][0]

    # 3. determine coordinates for printing central words:
    # at the central item
    if showwords: 
        clustertexts = [ ]
        for clusterindex, word in cluster_maxword.items():
            xcoord = twodim[ clustercentralpoints[clusterindex],0]
            ycoord = twodim[ clustercentralpoints[clusterindex],1]
            clustertexts.append( ( word, xcoord, ycoord) )
    else:
        clustertexts = None

    ### and visualize
    if clustercolors:
        pointcolors = clusterlabels
    else:
        pointcolors = None
    draw_points(df, twodim, pointcolors = pointcolors, bigtexts = clustertexts)

    return clusterlabels, cluster_maxword
